name: Update Blog Posts

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 16 * * *" # 오전 1시

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false # 기본 인증 제거

      - name: Configure Git
        run: |
          git config --global user.name 'cheonhy25u'
          git config --global user.email 'kor01chs@gmail.com'

      - name: Set GitHub Token
        run: echo "GH_PAT=${{ secrets.GH_PAT }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install feedparser gitpython

      - name: Run script
        run: python scripts/update_blog.py
